class Movie {
  final String? title,
      year,
      released,
      runTime,
      genre,
      director,
      writer,
      actors,
      plot,
      language,
      country,
      awards,
      rated,
      metaScore,
      imdbRating,
      imdbVotes,
      imdbID,
      type,
      dvd,
      boxOffice,
      production,
      website,
      response,
      poster,
      error;

  Movie(
      {this.error,
      this.title,
      this.year,
      this.released,
      this.runTime,
      this.genre,
      this.director,
      this.writer,
      this.actors,
      this.plot,
      this.language,
      this.country,
      this.awards,
      this.rated,
      this.metaScore,
      this.imdbRating,
      this.imdbVotes,
      this.imdbID,
      this.type,
      this.dvd,
      this.boxOffice,
      this.production,
      this.website,
      this.response,
      this.poster});

  factory Movie.fromJson(Map<String, dynamic> json) {
    return Movie(
      imdbID: json["imdbID"],
      poster: json["Poster"],
      title: json["Title"],
      year: json["Year"],
      type: json["Type"],
      released: json["Released"],
      runTime: json["Runtime"],
      genre: json["Genre"],
      director: json["Director"],
      writer: json["Writer"],
      actors: json["Actors"],
      plot: json["Plot"],
      language: json["Language"],
      country: json["Country"],
      awards: json["Awards"],
      rated: json["Rated"],
      metaScore: json["Metascore"],
      imdbRating: json["imdbRating"],
      imdbVotes: json["imdbVotes"],
      dvd: json["DVD"],
      boxOffice: json["BoxOffice"],
      production: json["Production"],
      website: json["Website"],
      response: json["Response"],
    );
  }
}
